UserController - wstępna implementacja endpointów
mryndak/project-jdp-2010-03 pull request #10
Opened 2020-10-24 19:01 UTC by Justynawoj

2020-10-25 16:01 UTC, robert-er requested changes

2020-10-25 16:42 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    private Long userId;
Dzieki. Dodałam kilka atrybutów do klasy User, czyli name, surname, nickname i email. Skasowalam klase z losowym ciagiem znakow i zastapilam ja 2 polami LocalDate do przechowywania czasu wygenerowania i String do przechowywania samego klucza.
Te pola docelowo bedą nadawane przez metody, dlatego nie są inicjalizowane przez konstruktor. Nie jestem pewna natomiast jakiego typu powinny być metody w controllerze i czy mogą zwracać zaktualizowanego usera, zakładając, że po wywołaniu odpowiednich metod te pola zostaną zaktualizowane. A może powinny być typu void, boolean albo String?

2020-10-25 19:35 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    public void createUser(@RequestParam String nickname,@RequestParam String name, @RequestParam String surname,@RequestParam String email){
Czy w tym przypadku nie lepiej byłoby użyć RequestBody UserDto userDto ?

2020-10-25 19:35 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/domain/User.java
> +public class User {
Przydałoby się, jednak z tego co pamiętam tworzenie encji podlega pod osobny task na Jirze.

2020-10-25 19:38 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    private Long userId;
Odnośnie Id do klas Dto to sam na początku tak zrobiłem, ale po krótkim namyśle usunąłem.

2020-10-25 20:16 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    public void createUser(@RequestParam String nickname,@RequestParam String name, @RequestParam String surname,@RequestParam String email){
Oczywiście że powinno być RequestBody! Dzięki!
Co do userId to ostatecznie go dodałam do klasy UserDto, wydaje mi się, że będzie potrzebny przy mapowaniu User <->UserDto

2020-10-25 20:23 UTC, mryndak requested changes

2020-10-25 20:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/User.java
> +public class User {
Tak dokładnie - powinniśmy to zostawić komuś innemu

2020-10-25 20:23 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    private boolean isBlocked = true;
raczej nie przypisywał bym tu wartości true na stałe, lepiej to przenieść do konstruktora i ustawić odpowiednio

2020-10-25 20:39 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/dto/UserDto.java
> +    private boolean isBlocked = true;
wyszłam z założenia, że przy rejestracji trzeba wygenerować i podać właściwy kod, aby odblokować konto użytkownika. Przeniosę do konstruktora tak jak radzisz :)

2020-10-27 05:52 UTC, robert-er approved these changes

2020-10-28 19:57 UTC, nikorenos approved these changes
jest ok

2020-10-28 20:50 UTC, mryndak approved these changes

2020-10-28 20:51 UTC, merged