JDP201003-12
mryndak/project-jdp-2010-03 pull request #12
Opened 2020-10-26 22:19 UTC by nikorenos

2020-10-27 05:44 UTC, robert-er approved these changes

2020-10-27 05:44 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "NAME")
Drobna uwaga: @Column(name = "NAME") jest nadmiarowe. Kolumna o nazwie name utworzy się automatycznie.

2020-10-27 05:44 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "PRICE")
jak wyżej

2020-10-27 05:44 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "AMOUNT")
jak wyżej

2020-10-27 07:47 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "NAME")
na pewno tworzy się dla wszystkich pól automatycznie? w kursie było podawane

2020-10-27 08:05 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "NAME")
U mnie działa automatycznie :) 
Dla testu dodałem u siebie adnotację @Column(name = "NAME")
Efekt: Hibernate: create table product_groups (id bigint not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=MyISAM

a teraz usuwam adnotację @Column , robię drop tabeli i odpalam apkę na nowo, żeby utworzyła tabelę na nowo. Efekt ten sam:
Hibernate: create table product_groups (id bigint not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=MyISAM

sprawdź jak masz u siebie i daj znać 👍

2020-10-27 10:44 UTC, mryndak requested changes

2020-10-27 10:44 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "PRODUCT_ID", unique = true)
Wystarczy samo ID

2020-10-27 10:44 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "NAME")
Adnotacja jest nadmiarowa

2020-10-27 10:44 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    private Double price;
Zły typ, kwot nie przechowujemy w Dobule

2020-10-27 10:44 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
Powinien być jakiś opis dla produktu, można zastanowić się też nad ilością dostępnych produktów, czy też nad zdjęciami produktu

2020-10-27 11:40 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
@nikorenos 

Proponuję podobnie jak w pliku ProductDto:

private Long id;
private String title;
private Long price;
private String description;
private Long quantity;

2020-10-28 13:46 UTC, robert-er approved these changes

2020-10-28 15:37 UTC, mryndak submitted a review, later dismissed

2020-10-28 15:37 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
Kwota nie powinna być Long, tylko BigDecimal

2020-10-28 18:23 UTC, KRZYSZTOFP1989 approved these changes

2020-10-28 20:36 UTC, Justynawoj approved these changes
Jest ok. Jedynie zmieniłabym nazwę quantity na quantityInStock czy available, bo w zestawieniu z ceną i nazwą produktu jest mylące

2020-10-28 21:33 UTC, robert-er requested changes

2020-10-28 21:33 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    //trzeba odkomentować po dodaniu encji Cart
Na masterze już są te encje, więc możesz odkomentować

2020-10-28 21:33 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    private Cart cart;*/
@ManyToMany(mappedBy = "products")
    private List<Cart> carts;

2020-10-28 21:33 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    private Group group;*/
@JsonBackReference
    @NotNull
    @ManyToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name="group_id")
    private Group group;

2020-10-28 21:33 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    private Order order;*/
@ManyToMany(mappedBy = "products")
    private List<Order> orders;

2020-10-28 23:59 UTC, robert-er approved these changes

2020-10-29 18:57 UTC, merged