Jdp201003 14 v2
mryndak/project-jdp-2010-03 pull request #14
Opened 2020-10-28 20:51 UTC by szymonkat

Encja Cart

2020-10-28 21:40 UTC, robert-er requested changes

2020-10-28 21:40 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    private User user;
W encji User już jest :

    @OneToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "cart_id")
    private Cart cart;

więc albo usuniemy z Cart albo z User

2020-10-28 21:40 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    private Order order;
Tak samo jak wyżej: w encji Cart już jest :
    @OneToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "cart_id")
    private Cart cart;

2020-10-29 19:29 UTC, mryndak requested changes

2020-10-29 19:29 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
>      @ManyToMany(cascade = { CascadeType.ALL })
Nie jest tu poprawne użycie: 
@ManyToMany(cascade = { CascadeType.ALL })

2020-10-29 19:45 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
>      @ManyToMany(cascade = { CascadeType.ALL })
Racja - zmieniam na: @ManyToMany(cascade = CascadeType.MERGE)

2020-10-29 20:02 UTC, mryndak approved these changes

2020-10-29 20:18 UTC, robert-er requested changes

2020-10-29 20:18 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    private Order order;
order jest do wywalenia stąd

2020-10-29 20:24 UTC, robert-er approved these changes

2020-10-29 20:25 UTC, merged