Jdp201003 4
mryndak/project-jdp-2010-03 pull request #2
Opened 2020-10-22 06:55 UTC by robert-er

2020-10-22 10:58 UTC, mryndak commented
Usuń proszę niepotrzebne pliki z commita

2020-10-22 11:01 UTC, mryndak requested changes

2020-10-22 11:01 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @GetMapping("get")
bez "get"

2020-10-22 11:01 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @GetMapping("getAll")
jak wyżej bez "getAll"

2020-10-22 11:01 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @PostMapping("add")
jak wyżej, bez "add"

2020-10-22 11:01 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @DeleteMapping("delete")
jw

2020-10-22 11:01 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @PutMapping("update")
jw

2020-10-22 11:01 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    private final OrderServiceImpl orderServiceImpl;
Proponowałbym to usunąć, jednak na przyszłość pamiętaj by używać typu interfejsu czyli: OrderService. Jednak nie widzę tutaj potrzeby używania interfejsów.

2020-10-25 20:29 UTC, mryndak approved these changes

2020-10-25 20:38 UTC, Justynawoj approved these changes

2020-10-25 20:39 UTC, merged

2020-10-29 19:22 UTC, robert-er reviewed
brakuje OrderController na masterze