Jdp201003 23 CartController
mryndak/project-jdp-2010-03 pull request #20
Opened 2020-10-30 09:19 UTC by robert-er

CartController

2020-10-30 15:41 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +     //   return productMapper.mapToProductDtoList(cartService.getElementsFromCart(id));
Zamiast komentować tutaj, lepiej utworzyć klase product mapper i dać jej implementacje, aby np. zwracała pustą listę

2020-10-30 16:49 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +     //   return productMapper.mapToProductDtoList(cartService.getElementsFromCart(id));
Wyrzuciłem komentarze i dodałem parę klas

2020-10-31 18:18 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                cartRepository.deleteById(id);
Ta metoda nie ma pojedynczej odpowiedzialnosci bo tworzy order i jednoczesnie kasuje stary koszyk. Wiem, że o to nam chodzi, ale może zmieniłabym chociaż nazwę metody na createOrderFromCartAndDeleteCart że bylo wiadomo o co chodzi  (bo w sumie nie wiem jak to lepiej rozwiązać), ewentualnie dla czytelności wyniosłabym metodę z kasowaniem poza metodę createOrder i tylko ją tam wywoływała. Wydaje mi się, że exception z linii 68 nie będzie nigdy wywołany, ale skoro jest, to może też powinno się anulować order który zrobił się w linii 64 przed wyrzuceniem exception?

2020-10-31 19:27 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +    public List<Product> getElementsFromCart(Long id) {
compilator nie krzyczy ze brakuje mu tutaj throws NotFoundException?

2020-10-31 19:30 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +    public void addProductToCart(Long id, Long productId) throws NotFoundException {
co jesli produkt istnieje, ale nie ma go na stanie - quantity jest 0?

2020-10-31 19:45 UTC, szymonkat approved these changes

2020-10-31 19:45 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    private final ProductMapper productMapper;
Czy to nie powinno być oznaczone adnotacją @Autowired ?

2020-10-31 19:45 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    private final ProductMapper productMapper;
Czy to nie powinno być oznaczone adnotacją @Autowired ?

2020-10-31 19:45 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +    private final OrderService orderService;
Czy to nie powinno być oznaczone adnotacją @Autowired ?

2020-10-31 19:45 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +    public List<Product> getElementsFromCart(Long id) {
No właśnie nie krzyczy, ale sam chyba również bym dodał throws.

2020-10-31 19:45 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/exception/NotFoundException.java
> +    public NotFoundException(String message) {
To dobry pomysł z wyrzucaniem Stringa - też u siebie to zastosuję.

2020-10-31 19:45 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    private final ProductMapper productMapper;
Czy to nie powinno być oznaczone adnotacją @Autowired ?

2020-10-31 19:48 UTC, szymonkat requested changes
small remarks

2020-10-31 20:02 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                cartRepository.deleteById(id);
Jeżeli orderRepository.findByUserId(cartRepository.findById(id).get().getUser().getId()).isPresent() zwróci false, tzn. że order się nie utworzył i nie ma co usuwaćwraz z pojawieniem się wyjątku w linii 68. 

cartRepository.deleteById(id) wyniosę do prywatnej metody.

2020-10-31 20:08 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +    public void addProductToCart(Long id, Long productId) throws NotFoundException {
to chyba będzie trzeba całkiem przerobić, bo podając samo productId nie ma informacji o zamawianej ilości.

2020-10-31 20:11 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    private final ProductMapper productMapper;
Jest @RequiredArgsConstructor, pola są final więc zostaną wstzyknięte przez konstruktor a nie przez pola. Poza tym IntelliJ podpowiada, że " Field injection is not recommended  " . Rozmawiałem kiedyś o tym z mentorem. To tak jakby nie używać geterów i seterów tylko odwoływać się do pola klasy przez Klasa.pole, a tak się przecież nie powinno robić.

2020-10-31 20:24 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                cartRepository.deleteById(id);
Ah faktycznie, przeciez to jest orderRepo. Nie wiem o czym ja myslalam

2020-10-31 21:07 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                cartRepository.deleteById(id);
Jeszcze jedna uwaga, bo przeszłam do drugiego CR i nic mi sie nie klei. Wydaje mi się, że ta metoda powinna być typu Cart i zwracać koszyk. A metoda @nikorenos powinna go przechwytywać i budować na tej podstawie Order i go zapisywać. Poprawcie mnie jeśli się mylę bo nie wiem jak to rozgryzc

2020-10-31 21:07 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +    public void addProductToCart(Long id, Long productId) throws NotFoundException {
Przerobiłem metody addProductToCart i deleteProductFromCart uwzględniając ilość, chociaż wydaje mi się że spora część kodu z tych metod powinna być przeniesiona do ProductService

2020-10-31 21:11 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +    public List<Product> getElementsFromCart(Long id) {
poprawione

2020-10-31 21:23 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                cartRepository.deleteById(id);
Dopisałem metodę createOrder w OrderServiceImpl, która tworzy nowy obiekt typu Order na podstawie obiektu typu Cart.

2020-10-31 21:25 UTC, szymonkat approved these changes

2020-11-01 00:11 UTC, nikorenos requested changes

2020-11-01 00:11 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                    if(productQuantity <= 0L) {
trzeba jeszcze powiększyć ilość dostępnych produktów w productRepository po usunięciu ich z koszyka

2020-11-01 00:11 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                                .forEach(p -> p.setQuantity(p.getQuantity() + quantity));
trzeba jeszcze pomniejszyć ilość dostępnych produktów w productRepository

2020-11-01 09:21 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public CartDto createCart(@RequestBody CartDto cartDto) {
getElementsFromCart nie zwraca całego cart tylko listę produktów.

2020-11-01 09:23 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<ProductDto> getElementsFromCart(@PathVariable Long id) {
Zrobiłem wg specyfikacji: pobranie elementów z pustego koszyka. Jeśli potrzebujesz metodę zwracającą cały cart, np do swojego OrderService, to mogę coś dorobić w service i nie trzeba tego udostępniać w API zewnętrznie.

2020-11-01 09:59 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                    if(productQuantity <= 0L) {
poprawione

2020-11-01 09:59 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +                                .forEach(p -> p.setQuantity(p.getQuantity() + quantity));
poprawione

2020-11-01 10:17 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public CartDto createCart(@RequestBody CartDto cartDto) {
bo tak ale gdyby zwracała cały koszyk to mielibyśmy dostęp i do Usera i do listy produktów, a wydaje mi się że przy tworzeniu nie potrzeba nic zwracać

2020-11-01 10:19 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<ProductDto> getElementsFromCart(@PathVariable Long id) {
właśnie od początku zastanawiałem się po co zwracać pusty koszyk, tym bardziej że przy tworzeniu koszyka w konstruktorze mamy już Usera i listę produktów, więc niezależnie czy jest pusty czy nie to i tak przyda się zwrócić wszystko nie tylko listę produktów, dlatego byłbym za zwróceniem całości, ale to może niech inni a przede wszystkim Adam się wypowie :)

2020-11-01 10:24 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<ProductDto> getElementsFromCart(@PathVariable Long id) {
Jak na stronie sklepu internetowego masz ikonkę koszyka, klikasz na nią a tam pokazuje "Koszyk jest pusty" - to chyba po to zwraca się pusty koszyk :)

2020-11-01 11:10 UTC, Justynawoj approved these changes

2020-11-01 12:56 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<ProductDto> getElementsFromCart(@PathVariable Long id) {
Ale nawet taki pusty koszyk nie jest pusty bo zawiera Usera i listę produktów, która jest pusta, poza tym jak User doda produkty i przeładuje stronę to powinno zwrócić koszyk z produktami a nie pusty. Na ten moment createCart zwraca pusty koszyk, tylko dziwne jakbyśmy przy każdym zwróceniu tworzyli nowy. Ale nie będę się przy tym upierał, najwyżej w testach wyjdzie.

2020-11-01 13:05 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<ProductDto> getElementsFromCart(@PathVariable Long id) {
Metoda będzie zwracała listę produktów albo listę pustą jak nie ma w koszyku produktów.  W klasie ProductMapper napisałem komentarz, że potrzebna implementacja. Nie robiłem żadnej implementacji, gdyż to wykracza poza tego taska. Lepiej jak implementację zrobi ktoś, kto robi taska do ProductController.

2020-11-01 13:49 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<ProductDto> getElementsFromCart(@PathVariable Long id) {
ok

2020-11-01 13:49 UTC, nikorenos approved these changes
jak dla mnie ok

2020-11-01 19:15 UTC, merged

2020-11-01 20:16 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public CartDto createCart(@RequestBody CartDto cartDto) {
Sa dwa podejścia - nic nie zwracamy nic lub zwracamy obiekt stworzony. Częściej dominuje podejście zwracania obiektu stworzonego, w tym przypadku CardDto.