JDP201003-24
mryndak/project-jdp-2010-03 pull request #21
Opened 2020-10-30 20:49 UTC by nikorenos

OrderController - rzeczywista implementacja metod

2020-10-31 17:32 UTC, robert-er requested changes

2020-10-31 17:32 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                orderDto.getId(),
mapToOrder używasz tylko przy okazji tworzenia nowych orderów. Myślę, że nie powinno się podawać wtedy ID, bo jest generowanie automatycznie, a jak podasz ID, które już istnieje w bazie danych to będzie konflikt.

2020-10-31 17:32 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +    public Order saveOrder(final Order order) { return orderRepository.save(order);}
brakuje mi tu jakiejś walidacji, np. sprawdzenia czy taki order jaki chcesz dodać już istnieje w bazie danych.

2020-10-31 17:32 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/repository/OrderRepository.java
> +    Order save(Order Order);
IntelliJ podpowiada: Unchecked overriding: return type requires unchecked conversion. Found 'com.kodilla.ecommerce.domain.Order', required 'S' 

ja bym to zrobił tak: 
@Override
'<S extends Order'> S save(S order);

(bez apostrofów)

2020-10-31 17:32 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @Autowired
I tu znowu IntelliJ podpowiada: Field injection is not recommended

@Autowired można usunąć i dodać final do pól. Masz adnotację @RequiredArgsConstructor, która załatwi wstrzykiwanie do pól zamiast @Autowired

2020-10-31 17:32 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @Autowired
jak wyżej

2020-10-31 17:32 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +    private OrderRepository orderRepository;
Tutaj podobnie jak w Controllerze, IntelliJ podpowiada: Field injection is not recommended

@Autowired bym usunął, dodał private final OrderRepository orderRepository;

a za adnotacją @Service @AllArgsConstructor albo @RequiedArgsConstructor

2020-10-31 19:35 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                orderDto.getId(),
przy generowaniu zamówienia zawsze będzie unikalne Id, poza tym jeśli id jest w konstruktorze to musi być także tutaj, a musi być w konstruktorze, aby móc pobrać zamówienia zapisane w bazie

2020-10-31 19:37 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +    public Order saveOrder(final Order order) { return orderRepository.save(order);}
nie ma takiej potrzeby bo zawsze generowane jest unikalne id zamówienia

2020-10-31 19:48 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/repository/OrderRepository.java
> +    Order save(Order Order);
nie wiem za bardzo o co chodzi z tym S, to chyba zbyt zaawansowane rzeczy jak na ten poziom nauki, w kursie było tak jak u mnie, ale ok mogę tak zrobić :)

2020-10-31 20:57 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
>      public OrderDto updateOrder(@PathVariable Long id, @RequestBody OrderDto orderDto) {
Id jest nieużywany

2020-10-31 20:58 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        if (orderService.getOrderById(id).isPresent()) {
Mozna tez zapis zrobić w jednej linii z wykorzystaniem Optionala orElseThrow...

2020-10-31 20:59 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/domain/Order.java
> +    public enum Status {
Proponowałbym wynieś enum do osobnej klasy skoro ma być publiczny.

2020-10-31 21:01 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/exception/OrderNotFoundException.java
> +        super(message);
Używałbym tylko jeden z konstruktorów i sama nazwa exceptionu mówi na tyle, ze message jest zbędny, a jak już coś to przekazywałbym id, dla ktorego był notfound.

2020-10-31 21:01 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                orderDto.getId(),
Tak, w tym przypadku lepiej ustawić null

2020-10-31 21:05 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +    public Order saveOrder(final Order order) { return orderRepository.save(order);}
Robertowi chodzi o to, ze ta sama metoda mozemy tworzyc obiekt jak i edytoowac. Temu mozna zapobiec ustawiajac w mapperze null dla ordera, o czym pisałem wcześniej.

2020-11-03 11:22 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                orderDto.getId(),
Pojawił się null, moim zdaniem teraz jest OK

2020-11-03 11:34 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +
Nie wiem czy ta zmiana jest konieczna, patrząc na to co wyżej napisał Adrian

2020-11-03 11:36 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +
Nie wiem czy ta zmiana jest konieczna, patrząc na to co wyżej napisał Adrian

2020-11-03 11:37 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +
Nie wiem czy ta zmiana jest konieczna, patrząc na to co wyżej napisał Adrian

2020-11-03 11:38 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +
Nie wiem czy ta zmiana jest konieczna, patrząc na to co wyżej napisał Adrian

2020-11-03 11:38 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +import com.kodilla.ecommerce.domain.Order;
nieużywany import

2020-11-03 11:38 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +}
Nie wiem czy ta zmiana jest konieczna, patrząc na to co wyżej napisał Adrian

2020-11-03 11:40 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +    }
Nie wiem czy ta zmiana jest konieczna, patrząc na to co wyżej napisał Adrian

2020-11-03 11:44 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private OrderStatus.Status status;
brakuje mi tu pola user

2020-11-03 11:45 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                orderDto.getStatus()
brak mapowania dla pola user

2020-11-03 11:46 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/repository/OrderRepository.java
> +    Order save(Order Order);
Też nie do końca rozumiem - moglibyśmy przegadać na spotkaniu :)

2020-11-03 11:47 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                order.getStatus());
brak mapowania dla pola user

2020-11-03 11:47 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                .map(t -> new OrderDto(t.getId(), t.getName(), t.getDescription(), t.getStatus()))
jak dodasz user do OrderDto, to tutaj też trzeba będzie dodać

2020-11-03 11:55 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +        foundOrder.setUser(order.getUser());
tutaj jest OK, ale mapper zwróci Ci obiekt typu Order z polem user = null

2020-11-03 12:00 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        orderService.getOrderById(id).orElseThrow(OrderNotFoundException::new);
ta metoda nie usuwa order z DB, tylko pobiera i nigdzie jej nie zwraca. Powinieneś użyć orderService.deleteOrderById(id)

2020-11-03 12:11 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +        return orderRepository.save(order);
w takiej formie, tworzysz w DB nowy wiersz z nowym ID , 

jak dasz return orderRepository.save(foundOrder); to będzie działać poprawnie

2020-11-03 13:06 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/repository/OrderRepository.java
> +    Order save(Order Order);
![image](https://user-images.githubusercontent.com/66044285/97988754-bfeeac80-1ddd-11eb-967e-ecd4c3edb021.png)

2020-11-03 13:13 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/repository/OrderRepository.java
> +    Order save(Order Order);
Tu znalazłem dobre wyjaśnienie:
https://stackoverflow.com/questions/41656483/how-to-remove-spring-crudrepository-unchecked-conversion-beside-using-suppress-a

2020-11-03 17:21 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private OrderStatus.Status status;
nie ma pola User, bo User nie wchodzi w skład konstruktora Order, wydaje mi się nie ma potrzeby dodawać Usera do konstruktora bo przecież po to dodajemy relację.

2020-11-03 17:21 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +    }
Jaka zmiana?

2020-11-03 18:45 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private OrderStatus.Status status;
no ale nie tworzysz anonimowego ordera tylko order na podstawie cart a cart jest przypisany do user. Kazdy order musi miec swojego wlasciciela czyli user

2020-11-03 19:52 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private OrderStatus.Status status;
No tak i po to jest relacja z Userem, Usera można odnaleźć po id przypisanym do Order. Można też dodać do konstruktora, ale wtedy chyba nie jest już potrzebna relacja z userem.

2020-11-03 20:11 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private OrderStatus.Status status;
Relacja jest potrzebna, Nie stworzysz pola typu User w Order jak nie będzie relacji. Mógłbyś jedynie przepisywać userId, ale to chyba nie o to chodzi, żeby coś ręcznie przepisywać, po to są relacje żeby część rzeczy działa się automatycznie.

2020-11-05 01:23 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/OrderDto.java
> +    private OrderStatus.Status status;
zgodnie z ustaleniami nie dajemy pól z relacji do klas Dto

2020-11-05 01:24 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                orderDto.getStatus()
jak wyżej

2020-11-05 01:24 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                order.getStatus());
jak wyżej

2020-11-05 01:24 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                .map(t -> new OrderDto(t.getId(), t.getName(), t.getDescription(), t.getStatus()))
jak wyżej

2020-11-05 01:24 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        orderService.getOrderById(id).orElseThrow(OrderNotFoundException::new);
poprawione

2020-11-05 01:25 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +        return orderRepository.save(order);
poprawione

2020-11-05 01:26 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +        foundOrder.setUser(order.getUser());
jak wyżej

2020-11-05 01:27 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        if (orderService.getOrderById(id).isPresent()) {
poprawione

2020-11-05 01:30 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/repository/OrderRepository.java
> +    Order save(Order Order);
dzięki, zgodnie ze wskazówkę całkowicie usunąłem save :)

2020-11-05 01:30 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
>      public OrderDto updateOrder(@PathVariable Long id, @RequestBody OrderDto orderDto) {
poprawiłem

2020-11-05 01:32 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
>  import java.util.ArrayList;
poprawione

2020-11-05 01:33 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Order.java
> +    public enum Status {
poprawiłem

2020-11-05 03:25 UTC, robert-er reviewed
Przetestowałem Twoje endpointy i wszystko działa generalnie wg starej bazy danych z relacjami ManyToMany. I teraz nie wiem czy chcesz tą wersję mergować a potem przerabiać na architekturę z dodatkowymi encjami CartItem i OrderItem czy też od razu sobie w tym pull requeście poprzerabiasz.

2020-11-05 04:41 UTC, nikorenos commented
> 
> 
> Przetestowałem Twoje endpointy i wszystko działa generalnie wg starej bazy danych z relacjami ManyToMany. I teraz nie wiem czy chcesz tą wersję mergować a potem przerabiać na architekturę z dodatkowymi encjami CartItem i OrderItem czy też od razu sobie w tym pull requeście poprzerabiasz.

To bym zmergował, a dodałbym nowego taska i nowy pull request.

2020-11-05 10:06 UTC, robert-er approved these changes

2020-11-05 16:10 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/domain/OrderStatus.java
> +    public enum Status {
Wydzieliłbym to jako po prostu OrderStatus a nie robił zagnieżdżenia :)

2020-11-05 16:11 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        return orderMapper.mapToOrderDto(orderService.updateOrderById(id, orderMapper.mapToOrder(orderDto)).orElseThrow(OrderNotFoundException::new));
Trochę to złożone, proponuję wydzielić poszczególne wyniki metod do zmiennych i je potem przekazywać do kolejnych metod :)

2020-11-05 16:14 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +        return Optional.of(orderRepository.save(foundOrder));
Po co opakowujesz to w optional? Czy sprawdziłeś w dokumentacji, czy w ogóle jest warunek, dla którego zwraca kiedykolwiek null?

2020-11-05 16:40 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        return orderMapper.mapToOrderDto(orderService.updateOrderById(id, orderMapper.mapToOrder(orderDto)).orElseThrow(OrderNotFoundException::new));
a może lepiej w ogóle usunąć id z parametru? chyba mniej zachodu będzie jak wszystko wpisze się w body

2020-11-05 16:42 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +        return Optional.of(orderRepository.save(foundOrder));
to jest po to aby działało orElseThrow w updateOrder w Controllerze. Sporo zachodu z tym chyba łatwiej i prościej rzucić wyjątek z ifem

2020-11-05 16:48 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/OrderStatus.java
> +    public enum Status {
tzn? nie wiem co masz na myśli

2020-11-05 17:35 UTC, szymonkat approved these changes
Przetestowałem endpointy i działają ok. Miałem małe problemy z bazą przy tworzeniu Ordera - program działał dopiero po dropie całej bazy, a Java wskazywała na problem z relacją user_id. Bardzo możliwe, że to dane testowe, bo po dropie nie jestem w stanie odtworzyć błędu.

2020-11-05 19:10 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/OrderStatus.java
> +    public enum Status {
Zamiast class tworzysz enum
![image](https://user-images.githubusercontent.com/66044285/98285541-fcb7d080-1fa2-11eb-9377-5ab778c5288d.png)

2020-11-05 22:28 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/OrderStatus.java
> +    public enum Status {
a ok, dzięki, nie spotkałem się z tym

2020-11-06 07:31 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        return orderMapper.mapToOrderDto(orderService.updateOrderById(id, orderMapper.mapToOrder(orderDto)).orElseThrow(OrderNotFoundException::new));
Akurat id przy update jest zasadny. Chodzi o samo wydzielenie zmiennych:
```
Order orderToUpdate = orderMapper.mapToOrder(orderDto);
Order updatedOrder = orderService.updateOrderById(id, orderToUpdate).orElseThrow(OrderNotFoundException::new)
orderMapper.mapToOrderDto(updatedOrder);

2020-11-06 07:33 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/OrderService.java
> +        return Optional.of(orderRepository.save(foundOrder));
Ale chodzi o to, że to nigdy nie rzuci tego wyjątku, bo metoda save nie zwraca nulla, co najwyżej sama rzuci wyjątkiem. Rzucanie wyjątku powinno być tam gdzie wyszukujesz order:
``` orderRepository.findById(orderId).get();```

2020-11-08 01:49 UTC, robert-er approved these changes
Wg mnie jest OK. Wszystkie endpointy działają w postmanie. 

Mógłbyś przy merge uwzględnić, że na masterze jest nowa wersja bazy danych i w razie czego nie nadpisywać encji starymi relacjami ?

2020-11-08 02:02 UTC, nikorenos commented
> 
> 
> Wg mnie jest OK. Wszystkie endpointy działają w postmanie.
> 
> Mógłbyś przy merge uwzględnić, że na masterze jest nowa wersja bazy danych i w razie czego nie nadpisywać encji starymi relacjami ?
jasne postaram się zrobić merge swojego brancha z masterem i to wszystko odpowiednio rozwiązać

2020-11-08 16:09 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    private final OrderServiceImpl orderService;
Korzystamy z typu interfejsu: `OrderService`

2020-11-08 16:10 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        orderService.getOrderById(id).orElseThrow(() -> new NotFoundException("Order id: " + id +
Po co pobierasz order przy usuwaniu? Wystarczy go tylko usunąć.

2020-11-08 16:12 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                .map(t -> new OrderDto(t.getId(), t.getName(), t.getDescription(), t.getUser().getId(), t.getStatus()))
mozna użyć metody: `mapToOrderDto`

2020-11-08 16:13 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/OrderServiceImpl.java
> +        return orderRepository.findById(orderId);
Myślę, że spójniej byłoby gdyby tylko serwis rzucał wyjatkami typu NotFound i zawsze zwracał Order. W tej chwili jedne metody zwracają Optional inne nie.

2020-11-08 21:28 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        orderService.getOrderById(id).orElseThrow(() -> new NotFoundException("Order id: " + id +
A nie trzeba sprawdzić czy na pewno jest taki w bazie? co jeśli będziemy chcieli usunąć nieistniejący?

2020-11-08 21:32 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    private final OrderServiceImpl orderService;
a dlaczego nie może być OrderServiceImpl?

2020-11-08 21:40 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/OrderServiceImpl.java
> +        return orderRepository.findById(orderId);
ok, poprawiłem

2020-11-08 21:40 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/OrderMapper.java
> +                .map(t -> new OrderDto(t.getId(), t.getName(), t.getDescription(), t.getUser().getId(), t.getStatus()))
poprawiłem

2020-11-09 06:48 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    private final OrderServiceImpl orderService;
`deleteById` po prostu sie wykkona, niezależnie czy encja jest czy jej nie ma. Jeśli chcesz to zrobić jak Ty to nie używaj metody deleteById, tylko delete i przekaz jej pobraną wcześniej encję.

2020-11-09 06:49 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        orderService.getOrderById(id).orElseThrow(() -> new NotFoundException("Order id: " + id +
deleteById po prostu sie wykkona, niezależnie czy encja jest czy jej nie ma. Jeśli chcesz to zrobić jak Ty to nie używaj metody deleteById, tylko delete i przekaz jej pobraną wcześniej encję.

2020-11-09 06:49 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    private final OrderServiceImpl orderService;
Dobrą praktyką jest korzystanie z typów intefejsów, bo jak będziesz chciał skorzystać z innej implementacji to zmieniasz to tylko w jednym meijscu, a nie w całej aplikacji :)

2020-11-09 06:51 UTC, adrianpaz commented
> Przetestowałem endpointy i działają ok. Miałem małe problemy z bazą przy tworzeniu Ordera - program działał dopiero po dropie całej bazy, a Java wskazywała na problem z relacją user_id. Bardzo możliwe, że to dane testowe, bo po dropie nie jestem w stanie odtworzyć błędu.
> Można by też skorzystać ze wspólnego NotFoundException zamiast OrderNotFoundException.

To jest normalne, jak się schemat bazy zmienia, to hibernate ma problem z updatem już istniejących tabel i trzerba je po prostu usunąć.

2020-11-09 07:22 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        orderService.getOrderById(id).orElseThrow(() -> new NotFoundException("Order id: " + id +
Ale jeśli przez pomyłkę podamy złe id to nie warto mieć informacji, że encja którą chcemy usunąć już nie istnieje?

2020-11-09 09:41 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    private final OrderServiceImpl orderService;
ok. dodałem, mam nadzieję, że teraz jest ok :)

2020-11-09 19:16 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +@CrossOrigin("*")
To jest zbędne :)

2020-11-09 19:23 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        Order orderToUpdate = orderMapper.mapToOrder(orderDto);
Tutaj w maperze ustawiasz puste items (nadpisujesz to ktore przyszly w dto), więc nie zostaną uwzględnione przy zapisie.

2020-11-10 22:24 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +        Order orderToUpdate = orderMapper.mapToOrder(orderDto);
ok, poprawiłem

2020-11-10 22:25 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +@CrossOrigin("*")
usunięte :)

2020-11-10 22:26 UTC, merged