Implementation product controller - first commit
mryndak/project-jdp-2010-03 pull request #22
Opened 2020-11-01 19:23 UTC by Justynawoj

2020-11-01 19:43 UTC, robert-er requested changes

2020-11-01 19:43 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +    public ProductDto getProduct(Long productId) throws Exception {
nie przekazujesz parametru productId, powinno być: 
@RequestMapping(method = RequestMethod.GET, value = "getProduct/{productId}")
public ProductDto getProduct(@PathVariable  Long productId)

2020-11-01 19:43 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      public void deleteProduct(Long productId) {
jak wyżej

2020-11-01 19:43 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      public ProductDto updateProduct(ProductDto productDto) {
tataj brakuje adnotacji RequestBody:

public ProductDto updateProduct(@RequestBody ProductDto productDto)

2020-11-01 19:43 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      public void createProduct(ProductDto productDto) {
jak wyżej:

public void createProduct(@RequestBody ProductDto productDto)

2020-11-01 19:43 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
> +        product.setOrders(productDto.getOrders());
2x robisz to samo: najpierw tworzysz product z danymi wstrzykiwanymi przez konstruktor poprzez productDto.get...

a potem te same dane ustawiasz seterami product.setXX(productDto.getXX())

albo konstruktor albo setery

2020-11-01 20:29 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +    public ProductDto getProduct(Long productId) throws Exception {
Proponuję trzymać się konwencji jaką przyjęliście w projekcie i używać: `@GetMapping`

2020-11-01 20:29 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getProducts")
`PostMapping`

2020-11-01 20:30 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +        return productMapper.mapToProductDto(productService.getProduct(productId).orElseThrow(Exception::new));
Wykorzystaj już istniejący exception: `NotFoundException`

2020-11-02 19:59 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/repository/ProductRepository.java
> +    boolean existsById(Long aLong);
Czy w tym przypadku nie lepiej byłoby zastąpić "aLong" nazwą zmiennej "id" ?

2020-11-03 16:55 UTC, szymonkat requested changes

2020-11-03 16:55 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/ProductDto.java
> +    private List<Order> orders;
Czy w tym przypadku potrzebujemy zaznaczonych pól w klasie DTO ?

2020-11-04 22:41 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +        productService.saveProduct(productMapper.mapToProduct(productDto));
metody createProduct i updateProduct robią praktycznie to samo, z tą różnicą, że jedna zwraca obiekt a druga nie.

2020-11-04 22:44 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/ProductDto.java
> +    private List<OrderItem> orders;
Moja sugestia , z DTO wyrzuciłbym listy carts i orders. Zastanów się do czego używasz tego DTO: tworzenie produktu i modyfikacja. W tym miejscu nie chcesz zmieniać listy kto zamówił/kupił ten produkt. To będą robiły inne kontrollery.

2020-11-04 22:46 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
> +        Product product = new Product(productDto.getId(),
ta metoda jest używana w kontrolerze w metodach createProduct i updateProduct. Trzeba jakoś rozwiązać problem, że createProduct nie potrzebuje ID a updateProduct potrzebuje ID

2020-11-08 17:10 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +    private final ProductServiceImpl productServiceImpl;
Jak został stworzony interfejs ProductService, to tu powinno się używać interfejsu a nie konkretnej implementacji. Po to w klasie ServiceConfig metoda createProductService zwracała obiekt typu ProductService, żeby tutaj można było użyć obiektu typu ProductService a nie konkretnej implementacji. Jak masz w całym programie użyte interfejsy a nie konkretne implementacje i będziesz chciała zmienić implementację serwisu a inną, to wystarczy zmienić beana w ServiceConfig i nie musisz przerabiać w całym programie w każdym miejscu gdzie się używa ten serwis.

2020-11-08 17:11 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/config/ServiceConfig.java
> +    protected ProductServiceImpl createProductService(ProductRepository productRepository) {
Tu bym zostawił tak jak było.

2020-11-08 17:17 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @JsonBackReference
Jak w programie jest więcej niż 1 para JsonManagedReference - JsonBackReference, to trzeba je ponazywać, tak żeby kompilator wiedział która adnotacja odnosi się do której. Po to jest to (value = "product-group").

Ogólnie to myślę, że będzie można zrezygnować całkiem z tych adnotacji o ile się ogarnie dobre DTO, które się nie będą zapętlały.

2020-11-08 17:19 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/CartItemMapper.java
> +    private final ProductServiceImpl productService;
tu bym zostawił tak jak było

2020-11-08 17:23 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/ProductServiceImpl.java
> +    public List<Product> getProducts(){
przydałaby się adnotacja @Override, jeśli implementujesz metodę z interfejsu.

2020-11-08 17:23 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/ProductServiceImpl.java
> +    public Product getProduct(final Long productId) {
jak wyżej, dorzuć @Override

2020-11-08 17:24 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/ProductServiceImpl.java
> +    public void deleteProduct(final Long productId){
jak wyżej

2020-11-08 17:24 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/ProductServiceImpl.java
> +    public Product saveProduct(final Product product){
jak wyżej

2020-11-08 17:24 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/ProductServiceImpl.java
> +    public Product updateProduct(final Long productId,final Product product) {
jak wyżej

2020-11-08 17:27 UTC, robert-er requested changes
Ostatni commit nie buduje się.
> Task :compileTestJava FAILED
/home/circleci/repo/src/test/java/com/kodilla/ecommerce/service/CartServiceImplTest.java:36: error: no suitable constructor found for Product(String,BigDecimal,String,long)
    private Product product = new Product("product_title",
                              ^
    constructor Product.Product() is not applicable
      (actual and formal argument lists differ in length)
    constructor Product.Product(Long,String,BigDecimal,String,Long,List<CartItem>,Group,List<OrderItem>) is not applicable
      (actual and formal argument lists differ in length)
/home/circleci/repo/src/test/java/com/kodilla/ecommerce/service/CartServiceImplTest.java:75: error: cannot find symbol
                .getQuantity();
                ^
  symbol:   method getQuantity()
  location: class Product
2 errors

FAILURE: Build failed with an exception.

2020-11-08 19:06 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/config/ServiceConfig.java
> +    protected ProductServiceImpl createProductService(ProductRepository productRepository) {
Zmieniłam, dzieki!

2020-11-08 19:06 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +    private final ProductServiceImpl productServiceImpl;
tu tez

2020-11-08 19:07 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @JsonBackReference
Póki co ponazywałam dwustronnie. Mam nadzieję że dobrze

2020-11-08 19:07 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/mapper/CartItemMapper.java
> +    private final ProductServiceImpl productService;
wróciło

2020-11-08 19:07 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/service/ProductServiceImpl.java
> +    public Product getProduct(final Long productId) {
poszło

2020-11-08 19:10 UTC, Justynawoj commented
> Ostatni commit nie buduje się.
> 
> > Task :compileTestJava FAILED
> > /home/circleci/repo/src/test/java/com/kodilla/ecommerce/service/CartServiceImplTest.java:36: error: no suitable constructor found for Product(String,BigDecimal,String,long)
> > private Product product = new Product("product_title",
> > ^
> > constructor Product.Product() is not applicable
> > (actual and formal argument lists differ in length)
> > constructor Product.Product(Long,String,BigDecimal,String,Long,List,Group,List) is not applicable
> > (actual and formal argument lists differ in length)
> > /home/circleci/repo/src/test/java/com/kodilla/ecommerce/service/CartServiceImplTest.java:75: error: cannot find symbol
> > .getQuantity();
> > ^
> > symbol:   method getQuantity()
> > location: class Product
> > 2 errors
> 
> FAILURE: Build failed with an exception.

Blokowały mnie testy, przeszły dopiero gdy przypisałam produkt do grupy

2020-11-08 19:46 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/ProductServiceImpl.java
> +        Product productToUpdate = productRepository.findById(productId).get();
Robisz Optional.get() bez sprawdzenia czy taki ID istnieje w bazie danych.
Zamiast get() możesz rzucić wyjątek 

  `  Product productToUpdate = productRepository.findById(productId)`
  `              .orElseThrow(() -> new NotFoundException("Product id: " + productId + " not found"));`

![image](https://user-images.githubusercontent.com/66044285/98482713-81088e80-2203-11eb-8f79-dad02a9524f0.png)

2020-11-08 20:07 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +        return cartItemMapper.mapToCartItemDtoList(cartService.getElementsFromCart(id));
Czy jesteś zmeergowana z masterem? Bo te zmiany tam już są. Poza tym, Twój pull request ma strasznie dużo zmian. Jeśli mimo domergowania wciąż te zmiany są widoczne to spróbuj zamknąć i otworzyć ponownie pull request.

2020-11-08 20:09 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/CartItemMapper.java
> +        item.setProduct(productService.getProduct(cartItemDto.getProduct().getId()));
Widze niespójnosc, jedne serwisu maja findById inne get, trzymałbym się jednej koonwencji :)

2020-11-08 20:18 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +    public void createProduct(@RequestBody ProductDto productDto) {
![image](https://user-images.githubusercontent.com/66044285/98483347-d47cdb80-2207-11eb-838e-a730affad352.png)
Nie umiem użyć tego endpointa. Jak dodajesz nowy produkt ? Co podajesz w body ?

2020-11-08 20:36 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +        return cartItemMapper.mapToCartItemDtoList(cartService.getElementsFromCart(id));
Użyłam opcji rebase current onto selected, git sam automatycznie zaznaczył sledzenie wszystkich plikow, zreflektowałam że przydałoby się to odznaczyć gdy było już po ptakach. Tak czy inaczej wyglada na to, że jestem zmergowana bo przy opcji merge dostaję informację Already up-to-date. 
Czyli proponujesz tylko zamknięcie i ponowne otworzenie tego brancha? Czy utworzenie nowego na którym będą tylko klasy związane z productControllerem?

2020-11-09 13:47 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +    public void createProduct(@RequestBody ProductDto productDto) {
Tutaj jest jakiś problem z groupId, po usunięciu adnotacji @NotNull i tworzeniu bez grupy wszystko działa jak powinno.

2020-11-09 14:08 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +    public void createProduct(@RequestBody ProductDto productDto) {
Jeżeli ustawimy cascade na detach, to wtedy w postmanie działa:
![postman_product](https://user-images.githubusercontent.com/33418999/98551228-5ec34f00-229d-11eb-9cd9-8738e9b4c47e.PNG)
Tylko wtedy trzeba przetestować zależności encji przy usuwaniu, modyfikowaniu itd.

2020-11-12 03:03 UTC, closed without merging