FIX-JDP201003-23 CartController
mryndak/project-jdp-2010-03 pull request #23
Opened 2020-11-02 11:59 UTC by robert-er

2020-11-02 12:09 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +        }
tego IFa chyba można wywalić bo jest już sprawdzanie czy produkt jest w karcie niżej przy okazji wyciągania ilości. 

I jak ten if wyleci, to już niepotrzebna metoda isProductInCart

2020-11-02 16:54 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> -public class GroupController {
Dlaczego usunąłeś ten kontroler?

2020-11-02 16:55 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +        cartRepository.findById(cartId)
Już pobrałeś cart, nie ma sensu robić tego kolejny raz :)

2020-11-02 16:55 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
> +        cartRepository.findById(cartId)
Tutaj to samo

2020-11-02 16:56 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
>          productRepository.findById(productId)
Mamy już pobrany product.

2020-11-02 16:57 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/service/CartServiceImpl.java
>                  .setQuantity(productRepository.findById(productId).get().getQuantity() + quantity);
I po raz 3 pobieramy :)

2020-11-02 20:26 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> -public class GroupController {
Moją intencją było niezmienianie tego pliku i pozostawienie go takim jakim jest na masterze.

2020-11-05 10:47 UTC, szymonkat requested changes

2020-11-05 10:47 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
Przy próbie usunięcia z koszyka większej ilości produktu niż w nim jest, nic się nie dzieje (zwraca jedynkę, a liczba rzeczy w koszyku pozostaje taka sama). Może dobrze byłoby tu wstawić jakiś exception ?

2020-11-05 10:47 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/domain/CartItem.java
> +    public CartItem(@NotNull Cart cart, @NotNull Product product, Long quantity) {
Tutaj się zastanawiałem czy quantity też nie powinno mieć adnotacji Notnull

2020-11-05 22:29 UTC, Justynawoj approved these changes

2020-11-06 01:58 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
naprawiłem to

2020-11-06 02:13 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +            cascade = CascadeType.ALL,
Koszyk się nie usuwa po usunięciu CartItem.

Przy okazji usunąłem obciążanie stanu magazynu przy dodawaniu cart item do koszyka i dopisałem metodę createOrder w Twoim serwisie i wtedy tam obciążam magazyn.

2020-11-06 07:37 UTC, adrianpaz commented
Branch ma konflikty. Domerguj sobie mastera i je rozwiąż :)

2020-11-06 07:40 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> -public class GroupController {
Rozumiem, te zmiany wynikaja z tego, ze nie jestes zaktualizowany z masterem. Po domergowaniu mastera powinno to zniknac :)

2020-11-06 07:45 UTC, szymonkat approved these changes

2020-11-07 00:20 UTC, merged