JDP201003-29 - first commit
mryndak/project-jdp-2010-03 pull request #25
Opened 2020-11-02 21:00 UTC by KRZYSZTOFP1989

2020-11-02 21:26 UTC, szymonkat requested changes

2020-11-02 21:26 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception {
Mateusz pisał mi w którymś review że powinienem używać RuntimeException.

2020-11-02 21:26 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>  @CrossOrigin(origins = "*")
Też dodałem to do swojego kontrolera, ale Adrian zwrócił mi uwagę że jest to niepotrzebne (i słusznie :D ).

2020-11-02 21:26 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group, Long> {
Czy nie powinno być tutaj adnotacji ?

2020-11-02 21:26 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +//                .collect(Collectors.toList());
Ten GroupMapper jest do przerobienia -> przede wszystkim podczas mapowania nie używasz argumentu metody, więc musisz to zmienić (tak jak np było w taskowym zadaniu kodilli).
return new TaskDto(task.getName(), task.getInt()) itd.
Wydaję mi się również że setProducts(new ArrayList<>) też nie jest poprawne. Dzisiaj już nie zdążę tego wytestować - jutro napiszę dlaczego.

2020-11-03 12:49 UTC, robert-er commented
Jestem lekko skołowany, bo JDP-201003-29 wg JIRA to CartController - błędy w implemetacji

a tutaj chyba robisz GroupController ? czyli JDP-201003-22

2020-11-03 12:50 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>  import java.util.List;
nieużywany import

2020-11-03 12:52 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception {
a poza tym nie lepiej korzystać z istniejącego NotFoundException i jako message podać co nie zostało znalezione a tak to każdy tworzy swoje exceptiony i zaraz ich będzie 20

2020-11-03 12:57 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        group.getName();
group.setName(groupDto.getName());

itd.

2020-11-03 12:58 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        groupDto.getName();
groupDto.setName(group.getName());
itd. dla innych pól

2020-11-03 12:59 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        groupDto.setProducts(new ArrayList<>());
tutaj zamiast zwracać pustą listę, mógłbyś pobrać z DB aktualną listę produktów przypisanych do grupy i przekazać ją do obiektu Dto

2020-11-03 13:00 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group, Long> {
@szymonkat jakiej ?

2020-11-03 13:00 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group, Long> {
już wszędzie zaczęliśmy używać extends JpaRepository

2020-11-03 13:02 UTC, robert-er requested changes
Kilka rzeczy do zmiany

2020-11-03 14:17 UTC, closed without merging

2020-11-03 16:58 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception {
Zmienione, ponieważ źle nazwałem branacha, przeniosłem go tutaj: https://github.com/mryndak/project-jdp-2010-03/pull/26

2020-11-03 16:58 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>  @CrossOrigin(origins = "*")
Zmienione, ponieważ źle nazwałem branacha, przeniosłem go tutaj: #26

2020-11-03 16:58 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group, Long> {
Zmienione, ponieważ źle nazwałem branacha, przeniosłem go tutaj: #26

2020-11-03 16:59 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +//                .collect(Collectors.toList());
Wciąż coś się nie spina, aktualizacja tutaj: #26

2020-11-03 17:00 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        groupDto.getName();
Zmienione, ponieważ źle nazwałem branacha, przeniosłem go tutaj: #26

2020-11-03 17:00 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        group.getName();
Zmienione, ponieważ źle nazwałem branacha, przeniosłem go tutaj: #26

2020-11-03 17:00 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        groupDto.setProducts(new ArrayList<>());
Wciąż coś się nie spina, aktualizacja tutaj: #26

2020-11-03 17:00 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group, Long> {
Ogarnięte