Jdp201003 22
mryndak/project-jdp-2010-03 pull request #26
Opened 2020-11-03 16:45 UTC by KRZYSZTOFP1989

2020-11-03 16:54 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Mam problem z tymi Mapperami, zamiast Product pobiera ProductDto id odwrotnie :(

2020-11-03 16:54 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Mam problem z tymi Mapperami, zamiast Product pobiera ProductDto id odwrotnie :(

2020-11-03 17:01 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Z tego co widzę w klasie GroupDto w konstruktorze masz List<Product>, a wyżej List<ProductDto>

2020-11-03 17:04 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Fakt, ale to IJ automatycznie mi zmienił, kiedy zmienię na ProductDto, to wciąż tego nie widzi :/

2020-11-03 17:05 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Dodatkowo w ProductDto którego używasz masz konstruktora z "id".

2020-11-03 18:42 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
ja bym zostawił id w Dto i wyświetlał go w jsonie zwracanym przez API a przy tworzeniu obiektu nie trzeba go mapować i wtedy id generuje się automatycznie

2020-11-04 11:32 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Poprawiłem, ale wciąż jest problem w zakomentowanych miejscach plus w mapToGroupDtoList. Nie mogę rozgryźć z czego wynika

2020-11-04 14:59 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Zrobiłem aktualizację z przykładowym ProductMapper. To jak będzie on wyglądał finalnie, musimy ustalić jeszcze z @Justynawoj :) Dzięki Szymon i Robert za wskazówki 👍

2020-11-04 15:06 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Usunąłem jeszcze nieużywane importy

2020-11-04 15:27 UTC, szymonkat approved these changes

2020-11-04 15:27 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +        }
@robert-er skomentował w moim user serwisie fajne ułatwienie żeby pozbyć się if"a. Te 6 linijek można zastąpić jedną:
 return repository.findById(id).orElseThrow(() -> new NotFoundException("Group not found"));

2020-11-04 15:28 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        Group group = new Group();
Nie przekazując id, w przypadku update, nie zaktualizujesz a stworzysz nową grupę.

2020-11-04 15:30 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Nie rozumiem pytania, mógłbyś dokładnie sprecyzować lub podać przykład.

2020-11-04 15:58 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
Nie miałem utworzonego ProductMapper, dlatego otrzymywałem listę produktów, zamiast ProduktDto – póki co dodałem więc "testowy" Mapper dla produktów :)

2020-11-04 16:10 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        Group group = new Group();
Zaktualizowałem :)

2020-11-04 16:11 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +        }
Faktycznie wygląda to schludniej, zaktualizowałem :D

2020-11-04 22:54 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        Group group = new Group();
no to teraz update działa ale create group nie działa :)

2020-11-05 03:18 UTC, nikorenos requested changes

2020-11-05 03:18 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    private final ProductMapper productMapper;
to będzie niepotrzebne jak usuniemy obiekty w relacji z Dto

2020-11-05 03:18 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    public GroupMapper(ProductMapper productMapper) {
jak wyżej

2020-11-05 03:18 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    }
pewnie się rozwiąże jak usuniemy obiekty w relacji z Dto

2020-11-05 03:18 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +    Group save (Group group);
IJ wyświetla Unchecked overriding: return type requires unchecked conversion. Found 'com.kodilla.ecommerce.domain.Group', required 'S' , można to naprawić usuwając ten wpis zgodnie z wyjaśnieniem tutaj: https://stackoverflow.com/questions/41656483/how-to-remove-spring-crudrepository-unchecked-conversion-beside-using-suppress-a

2020-11-05 03:18 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    @Autowired
to samo co w przypadku private GroupService groupServiceImpl;

2020-11-05 11:51 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @Autowired
A widzisz, robiłem wg. tego co było w kursie - zaktualizowałem :)

2020-11-05 11:52 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>      public GroupDto getGroup(@PathVariable Long groupId) throws NotFoundException {
Nie jest, usunąłem

2020-11-05 11:52 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>          this.products = products;
Pozbyłem się

2020-11-05 11:53 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +    public GroupMapper(ProductMapper productMapper) {
Pozbyłem się, wykorzystałem @RequiredArgsConstructor

2020-11-05 11:53 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +    Group save (Group group);
Ogarnięte

2020-11-05 11:57 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    @Autowired
Ogarnięte

2020-11-05 12:57 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        return groupDto;
Nie przepisujesz tu ID, w efekcie przy wywołaniu PUT updateGroup, zwracane jest ID=0
![image](https://user-images.githubusercontent.com/66044285/98243862-d5471080-1f6e-11eb-9221-e4b9bb236529.png)

2020-11-05 13:04 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
> +                .collect(Collectors.toList());
Miałem tu taki problem, jak testowałem PUT, to w tym miejscu wywalało nullpointerexception przy pustej liście products. To dziwne, bo GET działa, NullPointer wyskakiwał tylko przy PUT.
Zmodyfikowałem lekko metodę żeby oba endpointy działały:
    public List<ProductDto> mapToProductDtoList(final List<Product> productList) {
        if(productList == null || productList.isEmpty()) {
            return new ArrayList<>();
        }
        return productList.stream()
                .map(this::mapToProductDto)
                .collect(Collectors.toList());
    }

2020-11-05 13:09 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +        groupService.saveGroup(groupMapper.mapToGroup(groupDto));
metodą GET createGroup da się zrobić update istniejącego rekordu w bazie danych, jak w DTO poda się istniejące ID

2020-11-05 17:08 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @Autowired
tak wiem, też tak na początku zrobiłem ;)

2020-11-05 17:23 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>          this.products = products;
nadal jest jako pole a mamy @AllArgsConstructor

2020-11-05 20:36 UTC, Justynawoj commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +        groupService.saveGroup(groupMapper.mapToGroup(groupDto));
Możesz rozwinąć? Chodzi Ci o metodę PUT?

2020-11-05 20:39 UTC, Justynawoj approved these changes

2020-11-05 22:02 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +        groupService.saveGroup(groupMapper.mapToGroup(groupDto));
Nie, po prostu używasz GET createGroup  do zrobienia operacji update, podając w body ID jakie już istnieje w bazie danych. Metoda createGroup ma zatem dwie funkcje, a tak nie powinno być.

2020-11-07 09:02 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
> +                .collect(Collectors.toList());
Warunek isEmpty jest zbedny bo to wlasnie pusta lista, czyli new ArrayList() :)

2020-11-07 09:03 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
> +                .collect(Collectors.toList());
Natomiast ten problem najlepiej wyeliminować gdzie indziej - w group w polu productList powinno się od razu inicjalizowac listę, aby ona była na dzień dobry pusta a nie null.

2020-11-07 09:06 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        return groupDto;
Jak dobrze widze to dla geta jest tak samo.

2020-11-07 19:51 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
> +                .collect(Collectors.toList());
Dopisałem to w klasie Group

2020-11-07 19:52 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +        groupService.saveGroup(groupMapper.mapToGroup(groupDto));
Chyba udało się to ogarnąć

2020-11-07 19:52 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        return groupDto;
Poprawione

2020-11-07 19:52 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>          this.products = products;
Teraz powinno być git

2020-11-08 01:57 UTC, nikorenos submitted a review, later dismissed

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>      private List<ProductDto> products;
mieliśmy nie używać obiektów w relacji w Dto

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>  @NoArgsConstructor
nie ma potrzeby bezparametrowego konstrukora, tylko właśnie ze wszystkimi @AllArgsConstructor

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        groupDto.setProducts(productMapper.mapToProductDtoList(group.getProducts()));
to będzie niepotrzebne jak usuniemy obiekty w relacji z Dto

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    public Group updateGroup(final Group group) {
to powinno być jako saveGroup

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    public Group saveGroup(final Group group) throws NotFoundException {
to powinno być updateGroup (przy save nie trzeba obsługiwać wyjątku), poza tym rzucenie wyjątku można zrobić w jednej linii z .orElseThrow

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
>  public class ProductMapper {
wydaje mi się, że ProductMapper  będzie niepotrzebny w tym branchu jak się usunię listę produktów z GroupDto

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @GetMapping(value = "getGroups")
mieliśmy stosować samo @GetMapping bez value

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @PostMapping(value = "createGroup")
jak wyżej

2020-11-08 01:57 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @PutMapping(value = "updateGroup")
jak wyżej

2020-11-08 01:59 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>  @NoArgsConstructor
@nikorenos w mapperze jest wykorzystywany bezparametrowy konstruktor: linia 26 :       GroupDto groupDto = new GroupDto();

2020-11-08 02:07 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>      private List<ProductDto> products;
W tym wypadku bym zostawił listę produktów w DTO. Wyobrażam sobię, że ktoś używa tego endpointa do wyszukiwania produktów po grupie: znajdź wszystkie produkty z grupy "narzędzia" i wtedy endpoint zwraca wszystko co jest przypisane do narzędzia. ProductDto musiałoby zostać okrojone z wrażliwych danych takich jak ile zostało w magazynie i kto to kupił. Stworzyłbym dodatkowy ProductDto bez pola  private Long quantity;

2020-11-08 02:13 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    public Group updateGroup(final Group group) {
Update nie działa poprawnie. Nie sprawdzasz czy ID, które chcesz updatować istnieje w bazie danych. Jak podam jakieś ID, którego nie ma w bazie, to po prostu zapisze mi nowy rekord. Zobacz na screen z postmana:
![image](https://user-images.githubusercontent.com/66044285/98455402-5faa9280-2170-11eb-8d93-2d305255c181.png)

2020-11-08 17:53 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>      private List<ProductDto> products;
No to musimy podjąć jakąś decyzję, bo nie chcę mieć tego odbijanego w każdym commicie :) Ja też był to zostawił

2020-11-08 17:54 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +        groupDto.setProducts(productMapper.mapToProductDtoList(group.getProducts()));
Odniosłem się w komentarzu odnośnie GroupDto

2020-11-08 17:56 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    public Group updateGroup(final Group group) {
Naprawiłem, ale jeżeli ktoś ma pomysł jak napisać w ładniejszy sposób metodę save i update, to będę wdzięczny, bo ja już nie mam koncpecji. Z orElseThrow mam jakiś problem

2020-11-08 17:59 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    public Group saveGroup(final Group group) throws NotFoundException {
@nikorenos  szczerze mówiąc nie wiem, jak to napisać za pomocą .orElseThrow – możesz mnie oświecić :D A odnośnie samego save, to pytanie co chcemy. Powyższy kod ma za zadanie uniemożliwienie zrobienia update za pomocą metody createGroup według tego co wyżej pisał @robert-er. W przykładowym zadaniu w materiałach Kodilli z Taskiem, też jest samo save i możesz właśnie sobie robić update za pomocą metody create :)

2020-11-08 17:59 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @GetMapping(value = "getGroups")
Zapomniałem usunąć, jak sobie testowałem - usunięte

2020-11-08 17:59 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @PostMapping(value = "createGroup")
Zapomniałem usunąć, jak sobie testowałem - usunięte

2020-11-08 17:59 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @PutMapping(value = "updateGroup")
Zapomniałem usunąć, jak sobie testowałem - usunięte

2020-11-08 18:02 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/mapper/ProductMapper.java
>  public class ProductMapper {
Odniosłem się w komentarzu odnośnie GroupDto - ja bym to zostawił, ale jeżeli nie, to pozostaje pytanie co robimy, bo wciąż mi to odbijasz, a ja muszę mieć jakiś Mapper, aby w obecnej formie skompliować kod :)

2020-11-08 19:59 UTC, adrianpaz commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
>      private List<ProductDto> products;
Nie używamy aby nie robić zapętleń, ale tutaj lista ProductDto jak najbardziej ma sens, tylko ProductDto nie powinien mieć w sobie GroupDto a samo groupId, ani informacji o tym w jakim koszyku i orderze jest.

2020-11-08 20:31 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +        Optional groupId = repository.findById(id);
Tutaj IntelliJ podpowiada  warning: Raw use of parameterized class 'Optional' 
Możesz dać `Optional<Group> groupId - repository.findById(id);`

Wg mnie nazwa groupId jest myląca. Myślałem, że chodzi o ID grupy a tymczasem tam jest obiekt typu Group.

2020-11-08 20:31 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +        if (!groupId.isPresent()) {
zamiast `!groupId.isPresent()` można użyć `groupId.isEmpty()`

2020-11-08 20:33 UTC, robert-er approved these changes
Kosmetyczne uwagi, poza tym wszystkie endpointy działają.

2020-11-11 20:15 UTC, merged