created domain, dto object and CartController
mryndak/project-jdp-2010-03 pull request #3
Opened 2020-10-22 16:16 UTC by nikorenos

2020-10-22 19:52 UTC, mryndak requested changes

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void createCart(CartDto cartDto) {
Brakuje adnotacji @RequestBody

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<CartDto> getProductsFromCart() {
Powinny zostać zwrócone sztuczne dane - należy zbudować tutaj listę z odpowiedzią

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void addProductsToCart() {
Brakuje przekazania obiektu do aktualizacji

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void deleteProductFromTask() {
Brakuje przekazania id obiektu, który ma zostać usunięty

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void createOrderFromCart(CartDto cartDto) {
@RequestBody jw

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +public class Cart {
Powinien zostać dodany też seter

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +public class CartDto {
jw brakuje setera

2020-10-22 19:52 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
Koszyk powinien zawierać większą ilość pól, lub komentarz aby ktoś w przyszłości uzupełni koszyk o produkty

2020-10-22 22:00 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<CartDto> getProductsFromCart() {
A jak zwrócić listę produktów gdy nie jest zaimplementowana?

2020-10-22 22:13 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
a czy listy produktów nie będzie trzeba dodać tylko do Cart i potem relację @OneToMany Cart do Products? oczywiście komentarz można dodać ale chyba tylko w Cart

2020-10-23 18:58 UTC, szymonkat reviewed
Small remarks

2020-10-23 18:58 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void deleteProductFromTask() {
Czy zamiast "Task" nie powinno być "Cart"?

2020-10-23 18:58 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
Ja bym chyba dodał List<Product>, zastanawiam się jeszcze nad relacją którą wspomniałeś - czy w tym przypadku nie powinna być relacja wiele do wielu ?

2020-10-23 19:00 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
Chciałem wyżej napisać "Ja bym chyba dodał List<Product>.

2020-10-23 19:45 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void deleteProductFromTask() {
tak, dzięki poprawię

2020-10-23 19:58 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
Chciałem wyżej napisać "Ja bym chyba dodał List<Product>"

2020-10-23 21:00 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public List<CartDto> getProductsFromCart() {
wrzuć na listę jakieś śmieciowe dane, np dwie pozycje żeby było widać, że to metoda zwracająca więcej niż jeden produkt.

2020-10-28 13:44 UTC, robert-er approved these changes

2020-10-28 18:13 UTC, closed without merging

2020-10-28 18:14 UTC, nikorenos commented
to stary branch, aktualny to JDP201003-3_2 już zmergowany