JDP201003-35 Ograniczenie dostępu do endpointów
mryndak/project-jdp-2010-03 pull request #37
Opened 2020-11-14 16:03 UTC by robert-er

Do wszystkich endpointów modyfikujących dane w bazie danych wymagane jest podanie ID usera i KEY usera.

2020-11-14 18:14 UTC, Justynawoj commented
Czy nie lepiej byłoby sprawdzać w serwisie czy dany user nie jest zablokowany, niż podawać za kazdym razem genereted key? Ogólnie brakuje nam autentyfikacji, ale to już chyba wyższa szkoła jazdy jest

2020-11-15 09:10 UTC, robert-er commented
> Czy nie lepiej byłoby sprawdzać w serwisie czy dany user nie jest zablokowany, niż podawać za kazdym razem genereted key? Ogólnie brakuje nam autentyfikacji, ale to już chyba wyższa szkoła jazdy jest.
> EDIT: Chyba że autentyfikacja sama w sobie działa właśnie w ten sposób i do tego służy nam generetedKey

Sugerowałem się opisem zadania : (konieczne przekazanie klucza do endpointów modyfikujących dane).

2020-11-15 11:48 UTC, Justynawoj approved these changes

2020-11-15 19:17 UTC, szymonkat reviewed
Na razie przetestowałem tylko kontroler product, więc jutro będę kontynuował. 
Odnośnie uwag to na razie mam tylko 2 drobne punkty do rzeczy o których wcześniej ja zapomniałem:
1) Wartość abs z generowanego klucza (napisałem osobny komentarz)
2) Przy wpisywaniu za każdym razem id i klucza, zauważyłem że można by skrócić nazwę generatedKey do key.

2020-11-15 19:17 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/service/UserServiceImpl.java
> +            String key = String.valueOf(ThreadLocalRandom.current().nextInt(0, 4000000) + user.hashCode());
Dzisiaj pokazał mi się ujemny klucz, dlatego prośba o wrzucenie poprawki:
String key = String.valueOf(Math.abs(ThreadLocalRandom.current().nextInt(0, 4000000) + user.hashCode()));

2020-11-15 19:57 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/service/UserServiceImpl.java
> +            String key = String.valueOf(ThreadLocalRandom.current().nextInt(0, 4000000) + user.hashCode());
Uwzględniłem Twoje poprawki

2020-11-16 13:56 UTC, szymonkat approved these changes
Przetestowałem - dla mnie jest ok. Wiadomo że przy tak dużym zadaniu pojawiają się pytania, ale ten task nie miał sprecyzowanych wytycznych takich jak kto może wykonywać które taski itd. dlatego daję approve'a. 
PS Dobrze że ten kod doszedł na końcu, bo testowanie postmanem z doklejaniem usera i klucza zabiera sporo więcej czasu :smile:

2020-11-16 15:05 UTC, szymonkat requested changes
Napotkałem błąd w blokowaniu użytkownika - powinno żądać id usera którego chcemy zblokować, a w dodatku autoryzować operację userId i keyem.

2020-11-17 07:26 UTC, robert-er commented
> Napotkałem błąd w blokowaniu/odblokowywaniu użytkownika - powinno żądać id usera którego chcemy zblokować lub odblokować, a w dodatku autoryzować operację userId i keyem.

OK Szymon przerobiłem żeby każdy mógł blokować każdego. 
http://localhost:8080/v1/user/block/2?userId=444&key=1734175061
po block/ należy podać PathVariable user którego chcemy blokować a w Params userId i pasujący do niego key

2020-11-17 07:30 UTC, szymonkat approved these changes

2020-11-17 16:01 UTC, merged