Jdp201003 2
mryndak/project-jdp-2010-03 pull request #4
Opened 2020-10-23 01:03 UTC by szymonkat

JDP201003-2

2020-10-23 01:11 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
> +@Getter
Zapomniałem o seterze - będzie dodany

2020-10-23 01:18 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
> +public class GroupDto {
Zapomniałem o konstruktorze domyślnym - będzie dodany

2020-10-23 01:23 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +public class GroupController {
dorzuć metodę do usuwania grupy

2020-10-23 18:18 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +public class GroupController {
Chociaż pomogłoby to w testowaniu (bo nie trzeba by było usuwać ręcznie), to zastanawiam się czy jak mam określoną listę endpointów na której nie mam usuwania grupy, to czy mogę dołożyć go tak sam od siebie (nie kłóci się to z kluczowymi zasadami wytwarzania oprogramowania ? ).

2020-10-23 21:04 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +public class GroupController {
Fakt, nie ma w opisie endpointów, ale to by oznaczało, że raz wrzucona grupa do bazy danych zostanie tam na zawsze i baza będzie z czasem rosnąć i rosnąć w nieskończoność

2020-10-26 20:12 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +public class GroupMapper {
Czy usunąć tego Mappera, czy ma już pozostać? Nie jest potrzebny do wykonania tego tasku.

2020-10-26 20:17 UTC, mryndak requested changes

2020-10-26 20:17 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
ProductDTO

2020-10-26 20:17 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/group/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception{
wyjątki biznesowe dziedziczymy po RuntimeException

2020-10-26 20:17 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/mapper/GroupMapper.java
> +public class GroupMapper {
To jest poza zakresem zadania

2020-10-26 20:27 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
Nie do końca rozumiem - tą pustą klasę dorzuciłem tylko po to aby projekt się kompilował. Oprócz Product mam "swoje" klasy, które używam do kontrolera - GroupDto i Group. Czy mógłbym prosić o jakieś szczegóły ?

2020-10-27 13:21 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
@szymonkat  pobrałem sobie Twoje pliki i odpaliłem w IJ. W klasie GroupDto tworzysz listę produktów na podstawie klasy ProductDto, a nie Product. Klasa ProducDto jest już zmegrowana, więc możesz ją już wykorzystać. Moim zdaniem nie potrzebujesz ani klasy Product, ani Group w tym momencie (zadania z Encjami), ponieważ projekt kompiluje się mając tylko klasę ProductDto i GroupDto

2020-10-27 13:23 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
Dzięki za podpowiedź, masz rację. Wieczorem zrobię zmiany i wypchnę do mastera.

2020-10-27 19:12 UTC, Justynawoj approved these changes
Aprowuję. Widziałam tylko, że Robert sugerował w diagramie dodanie do grupy produktow atrybutu description, myślę że można dodać takie pole. Możesz zmergować też tak jak jest a jutro wspólnie możemy omówić pola pozostałych klas

2020-10-27 19:20 UTC, KRZYSZTOFP1989 approved these changes

2020-10-28 06:54 UTC, robert-er requested changes

2020-10-28 06:54 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    public GroupDto getGroup(@RequestParam Long groupId) throws GroupNotFoundException {
Wg mnie to jest niepoprawne. W fakiej formie musiałbyć wywołać endpointa np. dla id = 4: GET /v1/group/4?id=4. Zresztą jak wklepałem to w IntelliJ to podpowiada błąd w dymku po najechaniu na linijkę 26: Cannot resolve @PathVariable 'groupId' 

Powinno być @PathVariable zamiast @RequestParam i wtedy wywołanie endpointa wygląda tak: GET /v1/group/4

2020-10-28 07:04 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    public GroupDto getGroup(@RequestParam Long groupId) throws GroupNotFoundException {
Racja, wieczorem poprawię.

2020-10-28 07:38 UTC, robert-er approved these changes

2020-10-29 19:17 UTC, mryndak approved these changes

2020-10-29 19:23 UTC, merged