Jdp201003 14
mryndak/project-jdp-2010-03 pull request #6
Opened 2020-10-23 20:28 UTC by nikorenos

2020-10-23 20:42 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void deleteProductFromTask(@RequestParam Long productId) {
literówka w nazwie metody Task -> Cart

2020-10-23 20:42 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @OneToMany(
Wydaję mi się że w tym przypadku powinno być ManytoMany - dobrze by było jakby ktoś się jeszcze wypowiedział.

2020-10-23 20:42 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
Czy nie powinieneś od razu dodać pola do CartDto ?

2020-10-23 20:46 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @OneToMany(
mi się wydaje że koszyk jest jeden a produktów wiele

2020-10-23 20:46 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
jakiego pola? relacje dodaje się tylko do Cart z tego co się orientuje

2020-10-23 20:47 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
> +    public void deleteProductFromTask(@RequestParam Long productId) {
dzięki poprawię 👍

2020-10-23 20:49 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @OneToMany(
Jak Product będziemy traktować jako pojedynczą rzecz, którą można zamówić a nie jako typ produktu, którego może być wiele sztuk do zamówienia to bym zostawił OneToMany

2020-10-23 20:50 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +@Entity(name = "CART")
Moja propozycja, by trzymać się konwencji nazw encji w liczbie mnogiej. Class User, Entity USERS. Class Cart, entity CARTS

2020-10-23 20:54 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
>      private Long id;
Skoro w Cart jest pole id z adnotacją @GeneratedValue, to wywaliłbym id z Dto, żeby id mogło się samo generować. 

Dodałbym List<ProductDto> products

2020-10-23 20:59 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
Tak jak niżej zasugerował Robert - List ProductDto

2020-10-23 21:01 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @OneToMany(
Mnie po prostu zastanawiało co w przypadku gdy mamy wiele koszyków, a w nich różne produkty.

2020-10-23 21:06 UTC, szymonkat commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private Long id;
Przy okazji - widzę że ostatni commit nie przechodzi testów CircleCI. 
"FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details."

2020-10-24 16:49 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +@Entity(name = "CART")
Wychodziłem z założenia że dla jednego klienta może być tylko jeden koszyk, ale ok.

2020-10-25 05:26 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +@Entity(name = "CART")
ale koszyków będzie tyle ile userów czyli dużo ;)

2020-10-28 11:52 UTC, robert-er requested changes
Pull request zapewne się nie zmerguje jeśli nie przejdzie CI testów, a u Ciebie te testy nie przechodzą

2020-10-29 20:15 UTC, closed without merging