Jdp201003 13
mryndak/project-jdp-2010-03 pull request #7
Opened 2020-10-24 02:10 UTC by robert-er

Group entity

2020-10-24 18:26 UTC, mryndak requested changes

2020-10-24 18:26 UTC, mryndak commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
Nie możemy zmienić wersji, ponieważ CircleCi jeszcze nie wpiera tej wersji gradle

2020-10-24 18:26 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    private Cart cart;
Dany produkt może być w kilku koszykach

2020-10-24 18:26 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @JsonManagedReference
W jakim celu została użyta tu adnotacja: JsonManagedReference ?

2020-10-24 18:26 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +
Koszyk powinien należeć do jakiegoś użytkownika systemu - proponuję dodać tutaj komentarz: todo aby ktoś dorobił relację gdy będzie tworzył encje User, lub utwórz klasę User reprezentującą entity i dodaj tutaj relację.

2020-10-25 04:34 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @JsonManagedReference
żeby zwracany Json nie był zapętlony

2020-10-25 04:40 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +
w User jest :
    @OneToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "cart_id")
    private Cart cart;

2020-10-25 04:42 UTC, robert-er reviewed
pozmieniane wg uwag

2020-10-25 04:53 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    private Cart cart;
zmieniłem na ManyToMany

2020-10-27 01:17 UTC, nikorenos requested changes

2020-10-27 05:08 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    private String name;
Nie rozumiem. Jest taka kolumna o nazwie name. Kolumny w tej encji jakie się tworzą to id, name, description

2020-10-27 05:24 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
Ja to rozumiem tak, że produkt X może być w wielu egzemplarzach, czyli user1, user2, ... user100 mogą dodać do swojego koszyka ten sam produkt X i wtedy jest relacja ManyToMany.

2020-10-27 07:43 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    private String name;
chodzi mi o taki zapis @Column(name = "NAME")

2020-10-27 07:45 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
właśnie nie, bo produkty dodane do koszyka 1 są tylko w relacji z koszykiem 1, nie są w relacji do koszyka 2

2020-10-27 07:51 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    private String name;
No ale to się tworzy z automatu, najlepiej sam sobie przetestuj. Zobacz jak to u mnie w IntelliJ wygląda: 
![image](https://user-images.githubusercontent.com/66044285/97271990-93f98700-1831-11eb-8ff7-13459aef0b5f.png)

2020-10-27 07:56 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
Twoja wersja byłaby OK dla sytuacji, gdyby na listę produktów wrzucać pojedyncze produkty: Product1, Product2 ..  i wtedy User kupuje pojednyczy produkt, ale zwróc uwagę, że w klasie Product jest pole int amount, czyli ile tego produktu jest na sprzedaż. W takiej sytuacji user1 może kupić 20x product1, 10xproduct2, podobnie jak user2 może kupić 3xproduct1, 5xproduct2

2020-10-27 20:25 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
tak ale produkty są  jako pojedynczy obiekt bo nawet jeśli jest wiele sztuk danego produktu, bo to jest jako jedna encja tylko z inną ilością. Tak mi się przynajmniej wydaje.

2020-10-28 06:33 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
A mi się wydaje że ten sam typ produktu to jest jeden obiekt czyli jeden wiersz w tabeli i tam jest ilość. Jak ktoś coś kupi to po prostu modyfikujesz wartość w kolumnie ilość ale obierkt(wiersz) zostaje ten sam. Nie tworzysz kilku wierszy(obiektów) dla tego samego produktu.

2020-10-28 10:32 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
No właśnie o tym mówię :)

2020-10-28 11:41 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
No dobra, czyli teraz tak: jeden produkt może być w różnych koszykach. Jedyna różnica między produktami w różnych koszykach to pole quantity. Poza tym w jednym koszyku mogą być różne produkty. Czyli ManyToMany

2020-10-28 12:37 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
no tak ale tutaj należy ustalić relację, produkty z innych koszyków nie są w relacji z każdym koszykiem, są tylko w relacji ze swoim czyli OneToMany

2020-10-28 12:48 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
jeżeli z jednej strony będziesz miał List(<Product>) - lista produktów znajdująca się w koszyku, a z drugiej List(<Cart>) - lista koszyków w których znajduje się produkt , to jak z tego chcesz OneToMany zrobić ?

2020-10-28 12:50 UTC, nikorenos commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
a po co lista koszyków w których jest produkt?

2020-10-28 13:20 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    @ManyToMany(cascade = { CascadeType.ALL })
https://stackoverflow.com/questions/360959/database-table-structure-for-shopping-cart

cytuję:
To answer your question, you need 3 tables. One for your products, one for your packages and one to "link" products to packages. I'm assuming you've got the first two covered. The third is called a Many-To-Many relationship.

It should be called ProductsPackages and have two columns (PackageId and ProductId). You should create foreign key constraints to the Products and Packages tables.

Now, to add a product to a package you insert the id of each into the ProductsPackages table.

2020-10-28 18:15 UTC, KRZYSZTOFP1989 reviewed
Dla mnie OK, jeżeli finalnie ustalimy/potwierdzimy relacje pomiędzy klasami, daje Approve

2020-10-28 20:05 UTC, KRZYSZTOFP1989 approved these changes

2020-10-28 20:24 UTC, Justynawoj approved these changes

2020-10-28 20:45 UTC, mryndak approved these changes

2020-10-28 20:59 UTC, merged