Product Controller
mryndak/project-jdp-2010-03 pull request #8
Opened 2020-10-24 09:49 UTC by KRZYSZTOFP1989

2020-10-24 13:01 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "price")
ta linijka jest bezużyteczna, jeśli w column name podajesz to samo co nazwa pola. Bez adnotacji @Column, nazwa kolumny automatycznie utworzy się taka jak nazwa zmiennej.

2020-10-24 13:03 UTC, robert-er commented on src/main/java/com/kodilla/ecommerce/dto/ProductDto.java
> +    private Long id;
Wg mnie będzie zgrzyt, jak będziesz podawał ID w DTO, bo w encji masz automatyczne generowanie ID @GeneratedValue(strategy = GenerationType.AUTO) . Co się stanie jak wywołasz endpoint createProduct z IDkiem który już istnieje w bazie danych ? pewnie się wysypie.

2020-10-24 16:20 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "price")
Okej, w takich okolicznościach zostawię jedynie:

    @Column(name = "name")
    private String title;

bo tylko tutaj nazwa kolumny jest inna niż nazwa pola.

2020-10-24 16:24 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +    @Column(name = "price")
Przy encji zmienię także na liczbę mnogą: @Entity(name = "products")

Według tego, co zostało zaproponowane w commitcie Marcina

2020-10-24 16:47 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/dto/ProductDto.java
> +    private Long id;
Okej, to na ten moment usunę

2020-10-26 08:30 UTC, mryndak requested changes

2020-10-26 08:30 UTC, mryndak commented on build/resources/main/application.properties
> +spring.application.name=eCommerce
powyższe pliki łącznie z tym (jest w katalogu build) do usunięcia

2020-10-26 08:30 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
Ten plik jest poza zakresem Twojego zadania - mamy tutaj zrobić Product Controller, dla encji jest osobne zadanie

2020-10-26 08:30 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/dto/ProductDto.java
> +    private Long id;
Id może zostać, wystarczy ignorować to id przy tworzeniu obiektu entity

2020-10-26 08:49 UTC, KRZYSZTOFP1989 commented on src/main/java/com/kodilla/ecommerce/domain/Product.java
> +public class Product {
Usunięty

2020-10-26 13:08 UTC, mryndak commented
Nie wszystkie tematy zostały rozwiązane / poprawione - na przykład dalej znajdują się niepotrzebne pliki w pull request 
![image](https://user-images.githubusercontent.com/10712156/97176050-ad002a80-1794-11eb-86e7-8b48f1fff322.png)

2020-10-26 19:00 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
> +@RequestMapping("/v1/product")
Powinno być products

2020-10-26 19:00 UTC, mryndak approved these changes

2020-10-26 19:06 UTC, robert-er approved these changes

2020-10-26 19:10 UTC, merged